modLoader = "javafml"
loaderVersion = "[4,)"
license = "MPL-2.0"

[[mods]]
modId = "ukulib"
displayName = "ukulib"
version = "${version}"

logoFile = "assets/ukulib/icon.png"
authors = "uku"
description = "small utility library used in my mods"

[[dependencies.ukulib]]
modId = "minecraft"
type = "required"
versionRange = "[26.1-snapshot,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ukulib]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.0-alpha,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "ukulib-common.mixins.json"